version: '3.9'

services:

  service-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/coursopedia
    depends_on:
        service-db:
          condition: service_healthy
  
  service-db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=coursopedia
    ports:
      - "5432:5432"
    volumes:
      - coursopedia-data:/var/coursopedia/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coursopedia"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  coursopedia-data: